name: netflix-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - python-dotenv
  - ipykernel
  - notebook
  - ipywidgets
  - pip:
    - streamlit
    - google-cloud-bigquery
    - pandas-gbq
    - db-dtypes
    - pandas
    - numpy
    - scikit-learn
    - xgboost          # for shap
    - imbalanced-learn
    - shap
    - matplotlib
    - seaborn
    - pylint
    - black
    - kagglehub==1.0.0