name: netflix-env
channels:
  - defaults
dependencies:
  - pip
  - pip:
    - numpy
    - pandas
    - kagglehub 
  - python=3.11
  - python_abi=3.11
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1

